<?php
/**
 * Predefined dataset configurations for renderGraph.
 *
 * Available keys include:
 * - utilized_storage, total_storage
 * - block_height
 * - active_hosts, total_hosts
 * - contract_revenue
 * - burned_funds, total_burned_funds
 * - siafund_tax_revenue
 * - market_cap
 * - active_contracts, renter_collateral_locked, host_collateral_locked
 * - contracts_formed, renewed_contracts, failed_contracts, successful_contracts, unique_contract_renters
 * - circulating_supply
 * - utilization_percent, collateral_locked_percent
 * - avg_storage_price, avg_upload_price, avg_download_price
 * - storage_price, upload_price, download_price
 * - max_used_storage
 * - total_fees
 * - siacoin_volume, siafund_volume
 * - avg_difficulty, blocks_mined, unique_transaction_addresses
 */

$palette = [
    'teal'   => ['bg' => 'rgba(75, 192, 192, 0.2)',  'border' => 'rgba(75, 192, 192, 1)'],
    'pink'   => ['bg' => 'rgba(255, 99, 132, 0.2)',   'border' => 'rgba(255, 99, 132, 1)'],
    'blue'   => ['bg' => 'rgba(54, 162, 235, 0.2)',   'border' => 'rgba(54, 162, 235, 1)'],
    'yellow' => ['bg' => 'rgba(255, 206, 86, 0.2)',   'border' => 'rgba(255, 206, 86, 1)'],
    'purple' => ['bg' => 'rgba(153, 102, 255, 0.2)',  'border' => 'rgba(153, 102, 255, 1)'],
    'orange' => ['bg' => 'rgba(255, 159, 64, 0.2)',   'border' => 'rgba(255, 159, 64, 1)'],
    'gray'   => ['bg' => 'rgba(201, 203, 207, 0.2)',  'border' => 'rgba(201, 203, 207, 1)'],
];

return [
    'utilized_storage' => [
        'label' => 'Utilized Storage',
        'key' => 'utilized_storage',
        'backgroundColor' => $palette['teal']['bg'],
        'borderColor' => $palette['teal']['border'],
        'unit' => 'PB',
        'unitDivisor' => 1e15,
        'decimalPlaces' => 2,
        'startAtZero' => true,
    ],
    'total_storage' => [
        'label' => 'Total Storage',
        'key' => 'total_storage',
        'backgroundColor' => $palette['pink']['bg'],
        'borderColor' => $palette['pink']['border'],
        'unit' => 'PB',
        'unitDivisor' => 1e15,
        'decimalPlaces' => 2,
        'startAtZero' => true,
    ],
    'block_height' => [
        'label' => 'Block Height',
        'key' => 'block_height',
        'backgroundColor' => $palette['purple']['bg'],
        'borderColor' => $palette['purple']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'active_hosts' => [
        'label' => 'Active Hosts',
        'key' => 'active_hosts',
        'backgroundColor' => $palette['blue']['bg'],
        'borderColor' => $palette['blue']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'total_hosts' => [
        'label' => 'Total Hosts',
        'key' => 'total_hosts',
        'backgroundColor' => $palette['yellow']['bg'],
        'borderColor' => $palette['yellow']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => true,
        'hidden' => true,
    ],
    'contract_revenue' => [
        'label' => 'Contract Revenue',
        'key' => 'contract_revenue',
        'transform' => "return useFiat ? entry['contract_revenue'][currency] : entry['contract_revenue']['sc']/1e24;",
        'backgroundColor' => $palette['orange']['bg'],
        'borderColor' => $palette['orange']['border'],
        'fiatUnit' => 'USD',
        'scUnit' => 'SC',
        'fiatUnitDivisor' => 1,
        'scUnitDivisor' => 1,
        'decimalPlaces' => 2,
        'startAtZero' => true,
    ],
    'burned_funds' => [
        'label' => 'Burned Funds',
        'key' => 'burned_funds',
        'backgroundColor' => $palette['pink']['bg'],
        'borderColor' => $palette['pink']['border'],
        'transform' => "return useFiat ? (entry['burned_funds'] && entry['burned_funds'][currency] !== undefined ? entry['burned_funds'][currency] : null) : (entry['burned_funds'] && entry['burned_funds']['sc'] !== undefined ? entry['burned_funds']['sc'] / 1e24 : null);",
        'fiatUnit' => 'USD',
        'scUnit' => 'SC',
        'fiatUnitDivisor' => 1,
        'scUnitDivisor' => 1,
        'decimalPlaces' => 2,
        'startAtZero' => true,
    ],
    'siafund_tax_revenue' => [
        'label' => 'Siafund Tax Revenue',
        'key' => 'siafund_tax_revenue',
        'transform' => "return useFiat ? entry['siafund_tax_revenue'][currency] : entry['siafund_tax_revenue']['sc']/1e24;",
        'backgroundColor' => $palette['orange']['bg'],
        'borderColor' => $palette['orange']['border'],
        'fiatUnit' => 'USD',
        'scUnit' => 'SC',
        'fiatUnitDivisor' => 1,
        'scUnitDivisor' => 1,
        'decimalPlaces' => 2,
        'startAtZero' => true,
    ],
    'market_cap' => [
        'label' => 'Market Cap',
        'key' => 'market_cap',
        'transform' => "return entry['market_cap'] || null;",
        'backgroundColor' => $palette['yellow']['bg'],
        'borderColor' => $palette['yellow']['border'],
        'unit' => 'USD',
        'unitDivisor' => 1,
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'active_contracts' => [
        'label' => 'Active Contracts',
        'key' => 'active_contracts',
        'backgroundColor' => $palette['blue']['bg'],
        'borderColor' => $palette['blue']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'renter_collateral_locked' => [
        'label' => 'Renter Balance',
        'key' => 'renter_collateral_locked',
        'backgroundColor' => $palette['purple']['bg'],
        'borderColor' => $palette['purple']['border'],
        // Normalize to SC regardless of source (Hastings vs SC vs object)
        'transform' => "function norm(v){ if(v===null||v===undefined) return null; if(typeof v==='object'){ if(v.sc!==undefined && v.sc!==null) return Number(v.sc); if(v.hastings!==undefined && v.hastings!==null){ var h=Number(v.hastings); return isFinite(h) ? h/1e24 : null; } if(v.value!==undefined) v=v.value; } var n=Number(v); if(!isFinite(n)) return null; return n>1e18 ? n/1e24 : n; } return norm(entry['renter_collateral_locked']);",
        'unit' => 'SC',
        'unitDivisor' => 1,
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'host_collateral_locked' => [
        'label' => 'Host Collateral',
        'key' => 'host_collateral_locked',
        'backgroundColor' => $palette['orange']['bg'],
        'borderColor' => $palette['orange']['border'],
        // Normalize to SC regardless of source (Hastings vs SC vs object)
        'transform' => "function norm(v){ if(v===null||v===undefined) return null; if(typeof v==='object'){ if(v.sc!==undefined && v.sc!==null) return Number(v.sc); if(v.hastings!==undefined && v.hastings!==null){ var h=Number(v.hastings); return isFinite(h) ? h/1e24 : null; } if(v.value!==undefined) v=v.value; } var n=Number(v); if(!isFinite(n)) return null; return n>1e18 ? n/1e24 : n; } return norm(entry['host_collateral_locked']);",
        'unit' => 'SC',
        'unitDivisor' => 1,
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'contracts_formed' => [
        'label' => 'Contracts Formed',
        'key' => 'contracts_formed',
        'backgroundColor' => $palette['teal']['bg'],
        'borderColor' => $palette['teal']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'renewed_contracts' => [
        'label' => 'Renewed Contracts',
        'key' => 'renewed_contracts',
        'backgroundColor' => $palette['yellow']['bg'],
        'borderColor' => $palette['yellow']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'failed_contracts' => [
        'label' => 'Failed Contracts',
        'key' => 'failed_contracts',
        'backgroundColor' => $palette['pink']['bg'],
        'borderColor' => $palette['pink']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'successful_contracts' => [
        'label' => 'Successful Contracts',
        'key' => 'successful_contracts',
        'backgroundColor' => $palette['teal']['bg'],
        'borderColor' => $palette['teal']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'unique_contract_renters' => [
        'label' => 'Unique Contract Renters',
        'key' => 'unique_contract_renters',
        'backgroundColor' => $palette['blue']['bg'],
        'borderColor' => $palette['blue']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'circulating_supply' => [
        'label' => 'Circulating Supply',
        'key' => 'circulating_supply',
        'backgroundColor' => 'rgba(54, 162, 235, 0.2)',
        'borderColor' => 'rgba(54, 162, 235, 1)',
        'unit' => 'SC',
        'unitDivisor' => 1e24,
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'total_burned_funds' => [
        'label' => 'Total Burned',
        'key' => 'total_burned_funds',
        'backgroundColor' => $palette['pink']['bg'],
        'borderColor' => $palette['pink']['border'],
        'unit' => 'SC',
        'unitDivisor' => 1e24,
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'utilization_percent' => [
        'label' => 'Utilization %',
        'key' => 'utilized_storage',
        'backgroundColor' => 'rgba(75, 192, 192, 0.2)',
        'borderColor' => 'rgba(75, 192, 192, 1)',
        'transform' => "return entry['total_storage'] > 0 ? (entry['utilized_storage'] / entry['total_storage']) * 100 : 0;",
        'unit' => '%',
        'unitDivisor' => 1,
        'decimalPlaces' => 2,
        'startAtZero' => true,
    ],
    'collateral_locked_percent' => [
        'label' => 'Collateral/Supply Ratio',
        'key' => 'renter_collateral_locked',
        'backgroundColor' => 'rgba(255, 159, 64, 0.2)',
        'borderColor' => 'rgba(255, 159, 64, 1)',
        // Normalize possible Hastings/SC mixes: if a value is huge (>1e18) treat as Hastings. If inputs are null, return null (no data).
        'transform' => "function norm(v){ if (v===null || v===undefined) return null; var n=Number(v); if(!isFinite(n)) return null; return n>1e18 ? n/1e24 : n; } var r=norm(entry['renter_collateral_locked']); var h=norm(entry['host_collateral_locked']); var s=norm(entry['circulating_supply']); if (r===null || h===null || s===null || !isFinite(s) || s<=0) return null; var ratio=(r+h)/s; return isFinite(ratio) ? ratio : null;",
        'unit' => null,
        'unitDivisor' => 1,
        'decimalPlaces' => 6,
        'startAtZero' => true,
    ],
    'avg_storage_price' => [
        'label' => 'Storage',
        'key' => 'avg_storage_price',
        'backgroundColor' => $palette['teal']['bg'],
        'borderColor' => $palette['teal']['border'],
        // Convert to SC per TB-month, or to fiat using historical rates when available
        'transform' => "var v = (entry['avg_storage_price'] / 1e12 * 4320); if (useFiat && window.hostHistoricalRates) { var d = entry['date']; d = d.includes('T') ? d : d + 'T00:00:00Z'; var r = window.hostHistoricalRates[d] ? window.hostHistoricalRates[d][currency] : null; return r ? v * r : v; } return v;",
        'fiatUnit' => 'USD',
        'scUnit' => 'SC',
        'fiatUnitDivisor' => 1,
        'scUnitDivisor' => 1,
        'decimalPlaces' => 2,
        'startAtZero' => false,
    ],
    'avg_upload_price' => [
        'label' => 'Upload',
        'key' => 'avg_upload_price',
        'backgroundColor' => $palette['yellow']['bg'],
        'borderColor' => $palette['yellow']['border'],
        'transform' => "var v = (entry['avg_upload_price'] / 1e12); if (useFiat && window.hostHistoricalRates) { var d = entry['date']; d = d.includes('T') ? d : d + 'T00:00:00Z'; var r = window.hostHistoricalRates[d] ? window.hostHistoricalRates[d][currency] : null; return r ? v * r : v; } return v;",
        'fiatUnit' => 'USD',
        'scUnit' => 'SC',
        'fiatUnitDivisor' => 1,
        'scUnitDivisor' => 1,
        'decimalPlaces' => 2,
        'startAtZero' => false,
    ],
    'avg_download_price' => [
        'label' => 'Download',
        'key' => 'avg_download_price',
        'backgroundColor' => $palette['pink']['bg'],
        'borderColor' => $palette['pink']['border'],
        'transform' => "var v = (entry['avg_download_price'] / 1e12); if (useFiat && window.hostHistoricalRates) { var d = entry['date']; d = d.includes('T') ? d : d + 'T00:00:00Z'; var r = window.hostHistoricalRates[d] ? window.hostHistoricalRates[d][currency] : null; return r ? v * r : v; } return v;",
        'fiatUnit' => 'USD',
        'scUnit' => 'SC',
        'fiatUnitDivisor' => 1,
        'scUnitDivisor' => 1,
        'decimalPlaces' => 2,
        'startAtZero' => false,
    ],
    'max_used_storage' => [
        'label' => 'Used Storage',
        'key' => 'max_used_storage',
        'backgroundColor' => $palette['pink']['bg'],
        'borderColor' => $palette['pink']['border'],
        'unit' => 'TB',
        'unitDivisor' => 1e12,
        'decimalPlaces' => 2,
        'startAtZero' => false,
    ],
    'versions' => [
        'label' => 'Versions',
        'backgroundColor' => null,
        'borderColor' => null,
        'unit' => null,
        'unitDivisor' => 1,
        'decimalPlaces' => 0,
        'startAtZero' => false,
    ],
    'storage_price' => [
        'label' => 'Storage Price',
        'key' => 'storage_price',
        'backgroundColor' => $palette['orange']['bg'],
        'borderColor' => $palette['orange']['border'],
        'transform' => "var p = entry['storage_price']; var sc = (p && p.sc !== undefined) ? p.sc : p; var v = (sc / 1e12 * 4320); if (useFiat && window.hostHistoricalRates) { var d = entry['date']; d = d.includes('T') ? d : d + 'T00:00:00Z'; var r = window.hostHistoricalRates[d] ? window.hostHistoricalRates[d][currency] : null; return r ? v * r : v; } return v;",
        'fiatUnit' => 'USD',
        'scUnit' => 'SC',
        'fiatUnitDivisor' => 1,
        'scUnitDivisor' => 1,
        'decimalPlaces' => 2,
        'startAtZero' => true,
    ],
    'upload_price' => [
        'label' => 'Upload Price',
        'key' => 'upload_price',
        'backgroundColor' => $palette['purple']['bg'],
        'borderColor' => $palette['purple']['border'],
        'transform' => "var p = entry['upload_price']; var sc = (p && p.sc !== undefined) ? p.sc : p; var v = (sc / 1e12); if (useFiat && window.hostHistoricalRates) { var d = entry['date']; d = d.includes('T') ? d : d + 'T00:00:00Z'; var r = window.hostHistoricalRates[d] ? window.hostHistoricalRates[d][currency] : null; return r ? v * r : v; } return v;",
        'fiatUnit' => 'USD',
        'scUnit' => 'SC',
        'fiatUnitDivisor' => 1,
        'scUnitDivisor' => 1,
        'decimalPlaces' => 2,
        'startAtZero' => true,
    ],
    'download_price' => [
        'label' => 'Egress Price',
        'key' => 'download_price',
        'backgroundColor' => $palette['blue']['bg'],
        'borderColor' => $palette['blue']['border'],
        'transform' => "var p = entry['download_price']; var sc = (p && p.sc !== undefined) ? p.sc : p; var v = (sc / 1e12); if (useFiat && window.hostHistoricalRates) { var d = entry['date']; d = d.includes('T') ? d : d + 'T00:00:00Z'; var r = window.hostHistoricalRates[d] ? window.hostHistoricalRates[d][currency] : null; return r ? v * r : v; } return v;",
        'fiatUnit' => 'USD',
        'scUnit' => 'SC',
        'fiatUnitDivisor' => 1,
        'scUnitDivisor' => 1,
        'decimalPlaces' => 2,
        'startAtZero' => true,
    ],
    'used_storage' => [
        'label' => 'Utilized Storage',
        'key' => 'used_storage',
        'backgroundColor' => 'rgba(75, 192, 192, 0.2)',
        'borderColor' => 'rgba(75, 192, 192, 1)',
        'unit' => 'TB',
        'unitDivisor' => 1e12,
        'decimalPlaces' => 2,
        'startAtZero' => true,
    ],
    'total_fees' => [
        'label' => 'Total Fees',
        'key' => 'total_fees',
        'backgroundColor' => 'rgba(153, 102, 255, 0.2)',
        'borderColor' => 'rgba(153, 102, 255, 1)',
        'unit' => 'SC',
        'unitDivisor' => 1e24,
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'siacoin_volume' => [
        'label' => 'Siacoin Volume',
        'key' => 'siacoin_volume',
        'backgroundColor' => 'rgba(255, 159, 64, 0.2)',
        'borderColor' => 'rgba(255, 159, 64, 1)',
        'unit' => 'SC',
        'unitDivisor' => 1e24,
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'siafund_volume' => [
        'label' => 'Siafunds Volume',
        'key' => 'siafund_volume',
        'backgroundColor' => 'rgba(201, 203, 207, 0.2)',
        'borderColor' => 'rgba(201, 203, 207, 1)',
        'unit' => 'SF',
        'unitDivisor' => 1e24,
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'avg_difficulty' => [
        'label' => 'Average Difficulty',
        'key' => 'avg_difficulty',
        'backgroundColor' => 'rgba(99, 132, 255, 0.2)',
        'borderColor' => 'rgba(99, 132, 255, 1)',
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'blocks_mined' => [
        'label' => 'Blocks Mined',
        'key' => 'blocks_mined',
        'backgroundColor' => $palette['blue']['bg'],
        'borderColor' => $palette['blue']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'unique_transaction_addresses' => [
        'label' => 'Unique Transaction Addresses',
        'key' => 'unique_transaction_addresses',
        'backgroundColor' => $palette['yellow']['bg'],
        'borderColor' => $palette['yellow']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => true,
    ],
    'total_successful_contracts' => [
        'label' => 'Total Successful Contracts',
        'key' => 'total_successful_contracts',
        'backgroundColor' => $palette['teal']['bg'],
        'borderColor' => $palette['teal']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => false,
    ],
    'total_failed_contracts' => [
        'label' => 'Total Failed Contracts',
        'key' => 'total_failed_contracts',
        'backgroundColor' => $palette['pink']['bg'],
        'borderColor' => $palette['pink']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => false,
    ],
    'total_renewed_contracts' => [
        'label' => 'Total Renewed Contracts',
        'key' => 'total_renewed_contracts',
        'backgroundColor' => $palette['yellow']['bg'],
        'borderColor' => $palette['yellow']['border'],
        'decimalPlaces' => 0,
        'startAtZero' => false,
    ],
    'contract_filesize_total' => [
        'label' => 'Contract Filesize Total',
        'key' => 'contract_filesize_total',
        'backgroundColor' => $palette['teal']['bg'],
        'borderColor' => $palette['teal']['border'],
        'unit' => 'bytes',
        'unitDivisor' => 1,
        'decimalPlaces' => 0,
        'startAtZero' => false,
    ],
    'na_burned_funds' => [
        'label' => 'Burned Funds (Aggregates)',
        'key' => 'na_burned_funds',
        'backgroundColor' => $palette['pink']['bg'],
        'borderColor' => $palette['pink']['border'],
        'unit' => 'SC',
        'unitDivisor' => 1e24,
        'decimalPlaces' => 0,
        'startAtZero' => false,
    ],
];
