<?php
require_once dirname(__DIR__) . '/bootstrap.php';
require_once dirname(__DIR__) . '/include/layout.php';
include_once dirname(__DIR__) . '/include/graph.php';
$graphConfigs = require dirname(__DIR__) . '/include/graph_configs.php';

use Siagraph\Utils\ApiClient;
use Siagraph\Utils\Locale;
use Siagraph\Utils\CurrencyDisplay;

// fetch latest aggregates
$aggEndpoint = '/api/v1/daily/aggregates';
$latestData = ApiClient::fetchJson($aggEndpoint);
$dataError = !is_array($latestData);
$latest = $dataError ? [] : end($latestData);
$currencyCookie = CurrencyDisplay::selectedCurrency();
$asOf = !$dataError && isset($latest['date']) ? $latest['date'] : null;
$asOfText = $asOf ? ('Daily value as of ' . Locale::date($asOf)) : 'Daily value';
$rev = $latest['contract_revenue'] ?? null;
$contractRevenueValue = 'N/A';
if ($rev) {
    $contractRevenueValue = CurrencyDisplay::formatMonetary([
        'scValue' => isset($rev['sc']) ? ((float) $rev['sc'] / 1e24) : null,
        'fiatValue' => isset($rev[$currencyCookie]) ? (float) $rev[$currencyCookie] : null,
        'currency' => $currencyCookie,
        'date' => $asOf,
        'decimals' => 2,
        'scDecimals' => 2,
    ]);
}
$burn = $latest['burned_funds'] ?? null;
$burnedFundsValue = 'N/A';
if ($burn) {
    $burnedFundsValue = CurrencyDisplay::formatMonetary([
        'scValue' => isset($burn['sc']) ? ((float) $burn['sc'] / 1e24) : null,
        'fiatValue' => isset($burn[$currencyCookie]) ? (float) $burn[$currencyCookie] : null,
        'currency' => $currencyCookie,
        'date' => $asOf,
        'decimals' => 2,
        'scDecimals' => 2,
    ]);
}
$revenueDataset = $graphConfigs['contract_revenue'];
$revenueDataset['fiatUnit'] = strtoupper($currencyCookie);
$burnedDataset = $graphConfigs['burned_funds'];
$burnedDataset['fiatUnit'] = strtoupper($currencyCookie);

render_header('SiaGraph - Revenue & Burn', 'SiaGraph - Revenue & Burn', [
    '<link rel="stylesheet" href="' . htmlspecialchars(versioned_asset_url('css/pages/revenue.css'), ENT_QUOTES, 'UTF-8') . '">'
]);
?>
<section id="main-content" class="sg-container revenue-page">
    <section class="card revenue-hero">
        <div>
            <div class="revenue-hero__kicker">Network economics</div>
            <h1 class="revenue-hero__title">Revenue &amp; Burn</h1>
            <p class="revenue-hero__copy">
                Track contract revenue generated by network storage activity and funds removed from circulation through burn events, shown first in fiat with SC values kept available as context.
            </p>
            <?php if ($dataError): ?>
                <p class="revenue-hero__status">Latest aggregates unavailable.</p>
            <?php endif; ?>
        </div>
    </section>

    <section class="revenue-stat-grid" aria-label="Revenue summary">
        <article class="revenue-stat-card">
            <div class="revenue-stat-card__label"><i class="bi bi-cash-coin" aria-hidden="true"></i>Contract Revenue</div>
            <div class="revenue-stat-card__value"><?php echo $contractRevenueValue; ?></div>
            <div class="revenue-stat-card__context"><?php echo htmlspecialchars($asOfText, ENT_QUOTES, 'UTF-8'); ?></div>
        </article>
        <article class="revenue-stat-card">
            <div class="revenue-stat-card__label"><i class="bi bi-fire" aria-hidden="true"></i>Burned Funds</div>
            <div class="revenue-stat-card__value"><?php echo $burnedFundsValue; ?></div>
            <div class="revenue-stat-card__context"><?php echo htmlspecialchars($asOfText, ENT_QUOTES, 'UTF-8'); ?></div>
        </article>
    </section>

    <section class="card revenue-chart-card">
        <h2 class="card__heading">Contract Revenue &amp; Burned Funds</h2>
        <p class="revenue-section-copy">Monthly contract revenue and burned funds in the selected display currency. <a href="/siacoin_price">View SC exchange rate history →</a></p>
        <div class="card__content">
            <section class="graph-container">
                <?php
                renderGraph(
                    'revenue-burned',
                    [
                        $revenueDataset,
                        $burnedDataset
                    ],
                    'date',
                    '/api/v1/monthly/aggregates',
                    null,
                    'bar',
                    'month',
                    true,
                    'true',
                    12,
                    'false',
                    $currencyCookie
                );
                ?>
            </section>
        </div>
    </section>
</section>
<?php render_footer(); ?>
